kingbros/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stalls/',include('stalls.urls')),
    path('',include('pages.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
from stalls import views as stallviews
urlpatterns = [
    path('',views.HomePageView.as_view(),name='home'),
    path('about/',views.AboutPageView.as_view(),name='about'),
    path('contact/',views.ContactPageView.as_view(),name='contact'),
    path('thanks/',views.ThankYouView.as_view(),name='thanks'),
    path('photos/',views.PhotosView.as_view(),name='photos'),
]

stalls/urls.py
from django.urls import path
from .views import StallListView,StallDetailView,StallInfoRequest
urlpatterns = [
    path('',StallListView.as_view(),name='stall_list'),
    path('info/<slug:slug>/',StallDetailView.as_view(),name='stall_detail'),
    path('info/<slug:slug>/requestinfo',StallInfoRequest.as_view(),name='info_request'),
]

pages/models.py
from django.db import models

# Create your models here.
class Pic(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.name

stalls/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
# Create your models here.
class Stall(models.Model):
    Gravel = "Gravel"
    Concrete = "Concrete"
    name = models.CharField(max_length=200)
    description = models.TextField()
    floor_type = models.CharField(max_length=256,choices=[(Gravel, 'Gravel'),(Concrete,'Concrete')])
    door_height = models.DecimalField(max_digits=5,decimal_places=3)
    width = models.DecimalField(max_digits=5,decimal_places=3)
    length = models.DecimalField(max_digits=5,decimal_places=3)
    number_of_units = models.PositiveIntegerField()
    quarterly_rate = models.DecimalField(max_digits=6,decimal_places=2)
    pic = models.ImageField(upload_to='stall_pics/',blank=True,default="images/default_unit.jpg")
    slug = models.SlugField(null=True,blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('stall_list')

    def save(self):
        self.slug = slugify(self.name)
        return super().save()

stalls/forms.py
from django import forms

class ContactForm(forms.Form):

    name = forms.CharField()
    email = forms.EmailField()
    phone = forms.CharField()
    comments = forms.CharField(widget=forms.Textarea)

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from .models import Pic
# Create your views here.

class HomePageView(TemplateView):
    template_name = 'pages/home.html'

class AboutPageView(TemplateView):
    template_name = "pages/about.html"

class ContactPageView(TemplateView):
    template_name = "pages/contact.html"

class ThankYouView(TemplateView):
    template_name = "pages/thankyou.html"

class PhotosView(ListView):
    model = Pic
    template_name = 'pages/photos.html'

stalls/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic import DetailView,TemplateView
from django.views.generic.edit import FormView
from .models import Stall
from .forms import ContactForm
from django.core.mail import send_mail, EmailMessage
from django.template.loader import render_to_string
# Create your views here.
class StallListView(ListView):
    model = Stall
    template_name = "stalls/stalls_list.html"

class StallDetailView(DetailView):
    model = Stall
    template_name='stalls/stall_detail.html'

class StallInfoRequest(FormView):
    form_class = ContactForm
    template_name='stalls/get_more_info.html'
    success_url = reverse_lazy('thanks')
    def form_valid(self,form):
        clean_form = form.cleaned_data
        name = clean_form["name"]
        email = clean_form['email']
        phone = clean_form['phone']
        comment = clean_form['comments']
        message_body = render_to_string('pages/email.html',clean_form)
        send_mail(subject="Customer Inquiry",message=message_body,
                    from_email="jesseking96@yahoo.com",
                    recipient_list=["metalandhotdogs@yahoo.com",],
                    fail_silently=False)
        return super().form_valid(form)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/master.css" %}">
    {# <link rel="stylesheet" href="{% static "css/test.css" %}"> #}
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <title>{% block title %}King Bros Boat Storage{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home' %}">King Bros Boat Storage</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'stall_list' %}">Stalls<span class="sr-only">(current)</span></a>
      </li>
      <li class='nav-item'>
        <a class='nav-link' href="{% url 'photos' %}">Photos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About Us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contact' %}">Contact</a>
      </li>
    </ul>
  </div>
</nav>
  <div class="container">
    <div class="row">
    <div class="col-md-2">

    </div>
      <div class="col-md-8">
        {% block content %}

        {% endblock %}
      </div>
      <div class="col-md-2">
      </div>
      </div>
    </div>
  </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

templates/pages/about.html
{% extends "base.html" %}
{% load static %}
{% block title %}About Us{% endblock %}

{% block content %}
<div class="about-text">


  <h1 class="page-title"><u>About Us</u></h1>
  <img class='img-fluid about-image' src="{% static "images/about_us.jpg" %}" alt="">
  <p>King Bros. Boat Storage started by Randy King in 1984. The King family has been actively boating since the early 1940s. Randy and his brothers have been boating on Lake Lewisville/ Lake Dallas since 1953, and since 1987 have primarily owned offshore sport boats and drag boats. It was the need for convenient storage which led King Bros. to start their own storage business. At that time, there simply wasn’t a facility around to store hard-to-store boats. That’s where King Bros. comes in, catering to the guy with a 42’ Fountain, a jet ski and everything in between. King Bros. specializes in fishing boats, ski boats with towers, bass boats that require power outlets, offshore boats that need door height, plus the facility can easily accommodate the guy with a motor home, inside or outside.</p>
  <p>King Bros. is truly a family owned and operated facility! Randy King, the company founder, works on the property 7 days a week, and Paula King is in charge of leasing and office management. The Kings are friendly, knowledgeable folks who try to provide everything needed to enhance the boating experience for their customers. Try King Bros. Boat Storage and experience the hometown difference.</p>
  </div>
{% endblock %}

templates/pages/contact.html
{% extends "base.html" %}

{% block title %}Contact Us{% endblock %}
{% block content %}
<div class="jumbotron">
  <h3>We would love to hear from you!</h3>
  <h3>If you have any questions or comments, please call or email:</h3>
  <div class="contact">
  <p><strong>King Bros. Boat Storage</strong><br>965 Main St.<br>Hickory Creek, TX 75065 </p>
  <p><strong>Email:</strong> paula@kingbros.net</p>
  <p><strong>Office:</strong> 940-321-3685</p>
  <p><strong>Cell:</strong> 940-367-6224</p>
  </div>
  <iframe src="https://www.google.co.in/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=965+S.+Main+Hickory+Creek,+TX+75065&amp;aq=&amp;sll=21.125498,81.914063&amp;sspn=29.557822,53.569336&amp;ie=UTF8&amp;hq=&amp;hnear=965+Main+St,+Lake+Dallas,+Texas+75065,+United+States&amp;t=m&amp;z=14&amp;iwloc=A&amp;ll=33.108603,-97.0078&amp;output=embed&amp;iwloc=near" width="100%" height="350" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe>
  </div>
{% endblock %}

templates/pages/email.html
<p>Customer Name: {{clean_form.name}}</p>
<p>Customer Email: {{clean_form.email}}</p>
<p>Customer Phone: {{clean_form.phone}}</p>
<p>Customer Message: {{clean_form.comments}}</p>

templates/pages/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  {# <div class="jumbotron"> #}
    <h1 class="page-title">King Bros Boat Storage</h1>
    <img class="img-fluid home-image" src="{% static "images/aerial.jpg" %}" alt="Uh OH" height= 300px>
    <div class="home-text">


    <p>King Bros. Boat Storage is a family owned and operated company that has been in business since 1984. Being a family of very active boaters, the Kings understand the needs of all levels of boating enthusiasts, from first-time boat owners to seasoned pros. Whether you have a 42′ Fountain or a jet ski, King Bros. has a perfect accommodation for your craft!</p>

    <p>The facility is enclosed by a wrought iron fence with rolling gates. The security features provide peace-of-mind for clients, since there is an onsite security guard. Customers have safe and convenient 24-hour access to their storage units using an individual key code.</p>

    <p>We accept Visa, MasterCard, Discover and American Express!  One month free service with annual pre-payment!</p>
  {# </div> #}
  {# <div class="jumbotron"> #}
    <p class='center-header'>Other Amenities:

<ul class='no-bullets'>
  <li>Nicest boat storage facility on Lake Lewisville</li>
  <li>Wide drives</li>
  <li>20 acre facility, 24/7 access</li>
  <li>Boat ramp/Corp park adjacent to facility</li>
  <li>Onsite security, three infrared camera fields</li>
  <li>Dump station/air/water</li>
  <li>Two air conditioned nice bathrooms</li>
  <li>Electric doors on selected stalls (32′ and 64′ units)</li>
  <li>Three coded 45′ electric gates</li>
  <li>Camping park just across I-35</li>
  <li>All credit cards accepted</li>
</ul>

<p>Explore this site and learn why King Bros Boat Storage has kept many of the same loyal customers the whole time they’ve been open!</p>
</div>
  {# </div> #}
{% endblock %}

templates/pages/photos.html
{% extends "base.html" %}

{% block title %}Photos{% endblock %}

{% block content %}
<h1 class="page-title"><u>Photos</u></h1>
<div class="row">


{% for pic in pic_list %}
<div class="col-md-6">

  <img class='photo' src="{{pic.image.url}}" alt="Uh oh Spaghettio!">
  </div>
{% endfor %}
</div>
{% endblock %}

templates/pages/thankyou.html
{% extends "base.html" %}

{% block title %}Thank you{% endblock %}

{% block content %}
<h1>Thank you</h1>
<h3>We'll be in touch soon!</h3>
{% endblock %}

templates/stalls/get_more_info.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="info-form">
<h1>Request More Information</h1>
<h3>Please fill out the form below, and we'll be in touch soon.</h3>
<form id="info_form" method="post">
  {% csrf_token %}
  {{form|crispy}}
  <input type="submit" class="btn btn-primary" name="" value="Submit">
  {% endblock %}
</form>
</div>

templates/stalls/stall_detail.html
{% extends "base.html" %}
{% block title %}{{stall.name}}{% endblock %}

{% block content %}
<div class="jumbotron">


<img src="{{stall.pic.url}}" alt="Uh Oh" width=60%>
<h1>{{stall.name}}</h1>
<p>{{stall.description}}</p>
<a class='btn btn-primary' href="{% url 'info_request' slug=stall.slug %}">Request more information</a>
</div>
<h3>Specifications</h3>
<ul class="no-bullets">
  <li>Length: {{stall.length|floatformat}}'</li>
  <li>Width: {{stall.width|floatformat}}'</li>
  <li>Door Height: {{stall.door_height|floatformat}}</li>
  <li>Floor: {{stall.floor_type}}</li>
</ul>
{% endblock %}

templates/stalls/stalls_list.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron stalls-jumbo">


  <h1 class="page-title"><u>Explore Our Stalls</u></h1>
  <p>All of the stalls are designed with the average boater in mind, as each stall is at least 11.5 ft wide. Some some are almost 14′! There is plenty of backing room, and the drives are even wider in the areas with longer stalls. The Kings, too, are active boaters and have made it easy even for the first time boat owner to navigate backwards with plenty of room. There are even some drive thru stalls available.

There are stalls with gravel floors and also with concrete floors. All of the stalls have rolling doors with power in each and every one.</p>
</div>
<h3 class="units-header"><u>Available Units</u></h3>
<div class="row">


{% for stall in stall_list %}
<div class="col-md-6">
<div class="card" style="width: 18rem;">
<img src="{{stall.pic.url}}" class="card-img-top" alt="..." width=200px, height=200px>
<div class="card-body">
  <h5 class="card-title">{{stall.name}}</h5>
  {# <p class="card-text">{{stall.description|truncatechars:50}}</p> #}
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Length: {{stall.length|floatformat}}'</li>
    <li class="list-group-item">Width: {{stall.width|floatformat}}'</li>
    <li class="list-group-item">Door Height: {{stall.door_height|floatformat}}'</li>
    <li class="list-group-item">Floor Type: {{stall.floor_type}}</li>
  </ul>
  <a href="{% url 'stall_detail' slug=stall.slug %}" class="btn btn-primary">View</a>
</div>
</div>

</div>
{% endfor %}
</div>


{% endblock %}